### ISSUE TITLE
make DELETE-request rather than a POST-request to delete stuff

### ISSUE THREAD

**Issue by pauledenburg** [ri0t1985/api-creator#2]
At this moment you make a request to the /delete endpoint to delete the specified endpoint.

Going with REST, this should be a DELETE-request

**Comment by ri0t1985** [comment]
Thanks for reporting this issue, @pauledenburg. The issue has been fixed on the master branch, and will be fixed on the next release.

**Comment by ri0t1985** [comment]
This issue has been resolved in version 0.2
